config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

	root :to =>  "globals#home"

	# globlas
		get '/' => 'globals#home', as: :home
	
	# designers
		get '/designers/login' => 'designers#login', as: :login_designer
		post '/designers/session' => 'designers#create_session', as: :create_session_designer
		get '/designers/logout' => 'designers#destroy', as: :logout_designer
		get '/designers/define_password' => 'designers#define_password', as: :define_password_designer
		post '/designers/reset_password' => 'designers#reset_password', as: :reset_password_designer
		get '/designers/settings' => 'designers#settings', as: :settings_designer
		put '/designers/' => 'designers#update_settings', as: :update_settings_designer


		
		get '/designers/signup' => 'designers#new',  as: :signup_designer
		post '/designers' => 'designers#create' , as: :create_designer

		get '/clients/email_confirmation' => "callbacks#email_confirmation", as: :email_confirmation
		get '/designers/email_confirmation' => "callbacks#email_confirmation_designer", as: :email_confirmation_designer
	

	#businesses
		get '/businesses/email_confirmation' => "callbacks#email_confirmation_business", as: :email_confirmation_business
  		get '/businesses/define_password' => 'businesses#define_password', as: :define_password_business
		post '/businesses/reset_password' => 'businesses#reset_password', as: :reset_password_business
		get '/businesses/login' => 'businesses#login', as: :login_business
		post '/businesses/session' => 'businesses#create_session', as: :create_session_business
		get '/businesses/logout' => 'businesses#destroy', as: :logout_business
		get '/businesses/dashboard' => 'businesses#dashboard', as: :business_dashboard

		delete '/businesses/designers/:id' => 'businesses#delete_designer', as: :delete_designer_under_business
		post '/businesses/designers' => 'businesses#invite_designer', as: :invite_designer_under_business



  	#api
	namespace :api , :defaults => { :format => 'json' } do
    
    	post '/clients/sign_up', to: 'clients#sign_up'
    	post '/clients/sign_in', to: 'clients#sign_in'
    	delete '/clients/logout', to: 'clients#logout'

    end



end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController



	def invite_designer
		params["designer"]["business_id"] = current_business.id
		@designer = Designer.invite_designer(params)
		if @designer and  @designer.errors.empty?
		  redirect_to business_dashboard_path, notice: "Designer invited successfully"
		else
		  redirect_to business_dashboard_path, alert: "Please fill the form correctly!"
		  return
		end
	end

	def delete_designer
		designer = Designer.find_by(id: params["id"])
		designer.destroy
		redirect_to business_dashboard_path
	end

	def dashboard
		
	end

	def login
	end

	def create_session
	    unconfirmed_business = Business.find_by(unconfirmed_email: params["business"]["email"])
	    return redirect_to login_business_path, alert: "Business account not confirmed yet!" if unconfirmed_business
	    business = Business.find_by_email(params["business"]["email"])
	    if business && Utils.match_password(business.encripted_password, params["business"]["password"], business.salt)
	      session[:business_id] = business.id
	      redirect_to root_url
	    else
	      redirect_to login_business_path, alert: "Email or password is incorrect"
	    end
	end

	def define_password
	end

	def reset_password
	    business = Business.find_by(email: session[:current_email])
	    missing_fields = Utils.check_missing_fields(params, ["password", "password_confirmation"], "business")
	    return redirect_to define_password_business_path, alert: "Missing required fields"  if ( missing_fields.size > 0 )
	    return redirect_to define_password_business_path, alert: "Password and password confirmation don't match"  if params["business"]["password_confirmation"] !=  params["business"]["password"]
	    salt = BCrypt::Engine.generate_salt
	    encripted_password = BCrypt::Engine.hash_secret(params["business"]["password"], salt)
	    business.update( encripted_password: encripted_password, salt:salt, confirmation_token: Digest::SHA1.hexdigest([Time.now, rand].join))

	    redirect_to login_business_path, notice: "Password defined successfully"
	end

	def destroy
        session[:business_id] = nil
        session[:current_email] = nil
        redirect_to login_business_path
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/dashboard.html.erb
<div class="well">
	
	<h3>This is the dashboard page</h3>
	<div class="">
		<b>Busines's name: </b> <%= current_business.name %></i>
	</div><br>

	<img src="<%=current_business.picture.url%>"  width="150" >
	<br>
</div>
<hr>
<div class="panel panel-default">
  <div class="panel-heading">Designers</div>
  <div class="panel-body">
    <% current_business.designers.each do |designer| %>
    		<div class="row">
    			<div class="col-md-2">
    				<img src="<%=designer.picture.url%>" class="thumbnail" width="100">
    			</div>
    			<div class="col-md-3">
    				<%= designer.forename %>
    			</div>
    			<div class="col-md-4">
    				<%= designer.foreemail %> (<i><%= (designer.confirmation_token.present? ? "Pending" : "Confirmed") %></i>)
    			</div>
    			<div class="col-md-2">
    				<%= link_to "Delete", delete_designer_under_business_path(designer), method: :delete %> 
    			</div>
    		
    		</div>
    		
    <% end %>
  </div>
</div>


<%= form_tag invite_designer_under_business_path, method: :post  do %>
	<div class="row">
		<div class="col-md-5">
			<input class="form-control" placeholder="Ex: designer@appoint.me" name="designer[email]">
		</div>
		<div class="col-md-3">
			<button class="btn btn-info" type="submit">
				Invite designer to your business	
			</button>
		</div>
	</div>
<% end %>

<br>
<br>

app/views/businesses/define_password.html.erb
<div class="page-header">
	<h1>Define Your password</h1>
</div>

<%= form_tag reset_password_business_path, method: "POST", class: "js-form" do %>
	<div class="form-group">
		<label for="password">Password:</label>
		<input type="password" id="password" name="business[password]" class="form-control "/>
	</div>
	<div class="form-group">
		<label for="password_confirmation">Password Confirmation:</label>
		 <input type="password" name="business[password_confirmation]" class="form-control " />
	</div>
	<button type="submit" name="commit" class="btn btn-lg btn-danger" />Define Password</button>
<%end%>

app/views/businesses/login.html.erb
<div class="page-header">
	<h1>Access to your business account</h1>
</div>

<%= form_tag create_session_business_path, method: "POST", class: "js-form" do %>
	<div class="form-group">
		<label for="email">Email:</label>
		<input class="form-control validate[required, custom[email]]"  name="business[email]" type="text" />
	</div>
	<div class="form-group">
		<label for="password">Password:</label>
		<input type="password" id="password" name="business[password]" class="form-control validate[required]"/>
	</div>
	<button type="submit" name="commit" class="btn btn-lg btn-danger" />Enter</button>
<% end %>