config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

	root :to =>  "globals#home"

	# globlas
		get '/' => 'globals#home', as: :home
	
	# designers
		get '/designers/login' => 'designers#login', as: :login_designer
		post '/designers/session' => 'designers#create_session', as: :create_session_designer
		get '/designers/logout' => 'designers#destroy', as: :logout_designer
		get '/designers/define_password' => 'designers#define_password', as: :define_password_designer
		post '/designers/reset_password' => 'designers#reset_password', as: :reset_password_designer
		get '/designers/settings' => 'designers#settings', as: :settings_designer
		put '/designers/' => 'designers#update_settings', as: :update_settings_designer


		
		get '/designers/signup' => 'designers#new',  as: :signup_designer
		post '/designers' => 'designers#create' , as: :create_designer

		get '/clients/email_confirmation' => "callbacks#email_confirmation", as: :email_confirmation
		get '/designers/email_confirmation' => "callbacks#email_confirmation_designer", as: :email_confirmation_designer
	

	#businesses
		get '/businesses/email_confirmation' => "callbacks#email_confirmation_business", as: :email_confirmation_business
  		get '/businesses/define_password' => 'businesses#define_password', as: :define_password_business
		post '/businesses/reset_password' => 'businesses#reset_password', as: :reset_password_business
		get '/businesses/login' => 'businesses#login', as: :login_business
		post '/businesses/session' => 'businesses#create_session', as: :create_session_business
		get '/businesses/logout' => 'businesses#destroy', as: :logout_business
		get '/businesses/dashboard' => 'businesses#dashboard', as: :business_dashboard

		delete '/businesses/designers/:id' => 'businesses#delete_designer', as: :delete_designer_under_business
		post '/businesses/designers' => 'businesses#invite_designer', as: :invite_designer_under_business



  	#api
	namespace :api , :defaults => { :format => 'json' } do
    
    	post '/clients/sign_up', to: 'clients#sign_up'
    	post '/clients/sign_in', to: 'clients#sign_in'
    	delete '/clients/logout', to: 'clients#logout'

    end



end

app/models/designer.rb
class Designer < ApplicationRecord
    belongs_to :business
    has_many :appointments

	mount_uploader :picture, GeneralPictureUploader



	def self.confirm_email_designer(params)
		designer = self.find_by(confirmation_token: params["confirmation_token"])
		if designer
			self.where(unconfirmed_email: designer.unconfirmed_email).update_all(unconfirmed_email: "")
			designer.update(email: designer.unconfirmed_email, unconfirmed_email: "", confirmation_token: "", confirmed_at: Time.now) 
		end
		designer
	end

	def self.invite_designer(params)
    	missing_fields = Utils.check_missing_fields(params, ["email"], "designer")

        return if missing_fields.size > 0 or Designer.find_by(email: params["designer"]["email"])
        designer = Designer.find_by(email: params["designer"]["email"]) || Designer.find_by(unconfirmed_email: params["designer"]["email"])
        
        unless designer
            designer = Designer.new(    
                unconfirmed_email: params["designer"]["email"],
                business_id: params["designer"]["business_id"],
                confirmation_token: Digest::SHA1.hexdigest([Time.now, rand].join))
        end

    	if designer.save
    		MailerMailer.confirmation_email_designer(designer).deliver
    	end

    	designer
	end

    def forename
        (self.name.present? ? self.name : self.email)
    end


    def foreemail
        (self.email.present? ? self.email : self.unconfirmed_email)
    end



end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
    before_action :authorize, only: [:settings, :destroy]

    def settings
        
    end

    def update_settings
        missing_fields = Utils.check_missing_fields(params, ["name", "phone"], "designer")
        return redirect_to settings_designer_path, alert: "Missing required fields"  if ( missing_fields.size > 0 )
        current_designer.update(name: params["designer"]["name"],
                                phone: params["designer"]["phone"],
                                bio: params["designer"]["bio"]
                                )    
        current_designer.picture = params["designer"]["picture"]
        current_designer.save
        redirect_to settings_designer_path, notice: "Infos Updated successfully"
    end

    def login
    end

    def create_session
        unconfirmed_designer = Designer.find_by(unconfirmed_email: params["designer"]["email"])
        return redirect_to login_designer_path, alert: "Designer account not confirmed yet!" if unconfirmed_designer
        designer = Designer.find_by_email(params["designer"]["email"])
        if designer && Utils.match_password(designer.password, params["designer"]["password"], designer.salt)
          session[:designer_id] = designer.id
          redirect_to root_url
        else
          redirect_to login_designer_path, alert: "Email or password is incorrect"
        end
    end

	def new
		
    end

    def create
    	missing_fields = Utils.check_missing_fields(params, ["name","email", "password", "password_confirmation", "phone"], "designer")
    	return redirect_to signup_designer_path, alert: "Missing required fields"  if ( missing_fields.size > 0 )
    	return redirect_to signup_designer_path, alert: "Password and password confirmation don't match"  if params["designer"]["password_confirmation"] !=  params["designer"]["password"]
    	salt = BCrypt::Engine.generate_salt
		encrypted_password = BCrypt::Engine.hash_secret(params["designer"]["password"], salt)
    	designer = Designer.new(name: params["designer"]["name"],phone: params["designer"]["phone"],
    		unconfirmed_email: params["designer"]["email"], password: encrypted_password, salt:salt,
    		confirmation_token: Digest::SHA1.hexdigest([Time.now, rand].join))
    	if designer.save
    		MailerMailer.confirmation_email_designer(designer).deliver
    		session[:designer_id] = designer.id 
    		redirect_to root_url
    	else
    		redirect_to signup_designer_path
    	end
    end

    def define_password
    end

    def reset_password
        designer = Designer.find_by(email: session[:current_email])
        missing_fields = Utils.check_missing_fields(params, ["password", "password_confirmation"], "designer")
        return redirect_to define_password_designer_path, alert: "Missing required fields"  if ( missing_fields.size > 0 )
        return redirect_to define_password_designer_path, alert: "Password and password confirmation don't match"  if params["designer"]["password_confirmation"] !=  params["designer"]["password"]
        salt = BCrypt::Engine.generate_salt
        encrypted_password = BCrypt::Engine.hash_secret(params["designer"]["password"], salt)
        designer.update( password: encrypted_password, salt:salt, confirmation_token: Digest::SHA1.hexdigest([Time.now, rand].join))

        redirect_to login_designer_path, notice: "Password defined successfully"
    end

    def destroy
        session[:designer_id] = nil
        session[:current_email] = nil
        redirect_to login_designer_path
    end

end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/views/designers/define_password.html.erb
<div class="page-header">
	<h1>Define Your password</h1>
</div>

<%= form_tag reset_password_designer_path, method: "POST", class: "js-form" do %>
	<div class="form-group">
		<label for="password">Password:</label>
		<input type="password" id="password" name="designer[password]" class="form-control "/>
	</div>
	<div class="form-group">
		<label for="password_confirmation">Password Confirmation:</label>
		 <input type="password" name="designer[password_confirmation]" class="form-control " />
	</div>
	<button type="submit" name="commit" class="btn btn-lg btn-danger" />Define Password</button>
<%end%>

app/views/designers/login.html.erb
<div class="page-header">
	<h1>Login designer account</h1>
</div>

<%= form_tag create_session_designer_path, method: "POST", class: "js-form" do %>
	<div class="form-group">
		<label for="email">Email:</label>
		<input class="form-control validate[required, custom[email]]"  name="designer[email]" type="text" />
	</div>
	<div class="form-group">
		<label for="password">Password:</label>
		<input type="password" id="password" name="designer[password]" class="form-control validate[required]"/>
	</div>
	<button type="submit" name="commit" class="btn btn-lg btn-danger" />Login</button>
<% end %>

app/views/designers/new.html.erb
<div class="page-header">
	<h1>Signup</h1>
</div>

<%= form_tag create_designer_path, method: "POST", class: "js-form" do %>
	<div class="form-group">
		<label for="name">Name:</label>
		<input type="text" name="designer[name]" class="validate[required] form-control" />
	</div>
	<div class="form-group">
		<label for="phone">Phone:</label>
		<input type="text" name="designer[phone]" class="form-control validate[required,custom[onlyNumberSp]]" />
	</div>
	<div class="form-group">
		<label for="email">Email:</label>
		<input class="form-control validate[required,custom[email]]"  name="designer[email]" type="text" />
	</div>
	<div class="form-group">
		<label for="password">Password:</label>
		<input type="password" id="password" name="designer[password]" class="form-control validate[required]"/>
	</div>
	<div class="form-group">
		<label for="password_confirmation">Password Confirmation:</label>
		 <input type="password" name="designer[password_confirmation]" class="form-control validate[required,equals[password]]" />
	</div>
	<button type="submit" name="commit" class="btn btn-lg btn-danger" />Signup</button>
<%end%>

app/views/designers/settings.html.erb
<%= form_tag update_settings_designer_path, method: "PUT", class: "js-form", multipart: true do %>
	<div class="form-group">
		<img src="<%=current_designer.picture.url%>" class="thumbnail" width="100">
	</div>
	<div class="form-group">
		<label for="name">Change Profile picture:</label>
		<input name="designer[picture]" type="file" />
	</div>
	<div class="form-group">
		<label for="name">Name:</label>
		<input class="form-control validate[required]"  name="designer[name]" type="text" value="<%=current_designer.name%>"/>
	</div>
	<div class="form-group">
		<label for="name">Phone:</label>
		<input class="form-control validate[required,custom[phone]]"  name="designer[phone]" type="text" value="<%=current_designer.phone%>" />
	</div>
	<div class="form-group">
		<label for="name">Bio:</label>
		<textarea class="form-control validate[required]"  name="designer[bio]"><%=current_designer.bio%></textarea>
	</div>

	<button type="submit" name="commit" class="btn btn-lg btn-danger" />Update profile</button>
<% end %>