config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

	root :to =>  "globals#home"

	# globlas
		get '/' => 'globals#home', as: :home
	
	# designers
		get '/designers/login' => 'designers#login', as: :login_designer
		post '/designers/session' => 'designers#create_session', as: :create_session_designer
		get '/designers/logout' => 'designers#destroy', as: :logout_designer
		get '/designers/define_password' => 'designers#define_password', as: :define_password_designer
		post '/designers/reset_password' => 'designers#reset_password', as: :reset_password_designer
		get '/designers/settings' => 'designers#settings', as: :settings_designer
		put '/designers/' => 'designers#update_settings', as: :update_settings_designer


		
		get '/designers/signup' => 'designers#new',  as: :signup_designer
		post '/designers' => 'designers#create' , as: :create_designer

		get '/clients/email_confirmation' => "callbacks#email_confirmation", as: :email_confirmation
		get '/designers/email_confirmation' => "callbacks#email_confirmation_designer", as: :email_confirmation_designer
	

	#businesses
		get '/businesses/email_confirmation' => "callbacks#email_confirmation_business", as: :email_confirmation_business
  		get '/businesses/define_password' => 'businesses#define_password', as: :define_password_business
		post '/businesses/reset_password' => 'businesses#reset_password', as: :reset_password_business
		get '/businesses/login' => 'businesses#login', as: :login_business
		post '/businesses/session' => 'businesses#create_session', as: :create_session_business
		get '/businesses/logout' => 'businesses#destroy', as: :logout_business
		get '/businesses/dashboard' => 'businesses#dashboard', as: :business_dashboard

		delete '/businesses/designers/:id' => 'businesses#delete_designer', as: :delete_designer_under_business
		post '/businesses/designers' => 'businesses#invite_designer', as: :invite_designer_under_business



  	#api
	namespace :api , :defaults => { :format => 'json' } do
    
    	post '/clients/sign_up', to: 'clients#sign_up'
    	post '/clients/sign_in', to: 'clients#sign_in'
    	delete '/clients/logout', to: 'clients#logout'

    end



end

app/views/layouts/_header.html.erb
<div class="header">
	<%= link_to "Appoint-me", root_url, class:"pull-left menu-item" %>


	<% if not current_designer and not current_business %>
		<%#= link_to "Signup as designer", signup_designer_path , class:"pull-right menu-item" %>
		<%= link_to "Login as designer", login_designer_path , class:"pull-right menu-item" %>
		<%= link_to "Business space", login_business_path , class:"pull-right menu-item" %>
	<% end %>

	<% if current_business %>
		<%= link_to "Logout", logout_business_path, class:"pull-right menu-item" %>
		<%#= link_to "Settings", settings_designer_path, class:"pull-right menu-item" %>
		<div class="pull-right menu-item">
			<img src="" style="<%= "background-image:url(#{current_business.picture.url })" if current_business.picture.present? %>" class="user-picture" width="25" height="25">
		</div>
		<div class="pull-right menu-item">
			<i><%=link_to "#{current_business.name} dashboard", business_dashboard_path  %></i>
		</div>
	<% end %>
	
	<% if current_designer %>

		<%= link_to "Logout", logout_designer_path, class:"pull-right menu-item" %>
		<%= link_to "Settings", settings_designer_path, class:"pull-right menu-item" %>
		<div class="pull-right menu-item">
			<img src="" style="<%= "background-image:url(#{current_designer.picture.url })" if current_designer.picture.present? %>" class="user-picture" width="25" height="25">
		</div>
		<div class="pull-right menu-item">
			Hi <i><%= current_designer.forename %></i>, 
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render partial: "layouts/header" %>
    
    <div class="container" role="main">

      
      <%if alert.present? %>
        <div class="alert alert-warning">
          <strong><p id="alert"><%= alert %></p></strong>
        </div>
      <%end%>

      <%if notice.present? %>
        <div class="alert alert-info">
          <strong><p id="alert"><%= notice %></p></strong>
        </div>
      <%end%>

      <%= yield %>

    </div>
  </body>
</html>